[package]
name = "rust-matrix-multiply"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bench_matrix_mul_cpu"
harness = false
